# Generated by Django 6.0.4 on 2026-04-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0002_alter_profilemodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bmr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
